name: flutter_html_video
description: This extension package allows the <video> tag to be rendered using the flutter_html package
version: 3.0.0
homepage: https://github.com/Sub6Resources/flutter_html

environment:
  sdk: ">=3.2.0 <4.0.0"
  flutter: ">=3.3.0"

dependencies:
  flutter:
    sdk: flutter
  html: '>=0.15.0 <1.0.0'
  flutter_html:
    path: ../../../html
  video_player: '>=2.8.3 <3.0.0'
  chewie: '1.7.5'

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

funding:
  - https://opencollective.com/flutter_html

topics:
  - html
  - css
  - video
  - widgets
  - flutter_html
